configfile: 'config.yaml'

include: 'rules/build_phylogeny.smk'


rule all:
    input:
        rules.build_tree.output
        # bestTree = f"{ RAXML_OUTPUT_FOLDER }/RAxML_bestTree.{ config['raxml_output_name'] }",
        # bipartitions = f"{ RAXML_OUTPUT_FOLDER }/RAxML_bipartitions.{ config['raxml_output_name'] }",
        # BranchLabels = f"{ RAXML_OUTPUT_FOLDER }/RAxML_bipartitionsBranchLabels.{ config['raxml_output_name'] }",
        # bootstrap = f"{ RAXML_OUTPUT_FOLDER }/RAxML_bootstrap.{ config['raxml_output_name'] }",
        # info = f"{ RAXML_OUTPUT_FOLDER }/RAxML_info.{ config['raxml_output_name'] }"
        #

# rule all:
#     input:
#         get_output()
#         rules.build_tree.output
#         # bestTree = f"{RAXML_OUTPUT_FOLDER}/RAxML_bestTree.{config[raxml_output_name]}",
#         # bipartitions = f"{RAXML_OUTPUT_FOLDER}/RAxML_bipartitions.{config[raxml_output_name]}",
#         # BranchLabels = f"{RAXML_OUTPUT_FOLDER}/RAxML_bipartitionsBranchLabels.{config[raxml_output_name]}",
#         # bootstrap = f"{RAXML_OUTPUT_FOLDER}/RAxML_bootstrap.{config[raxml_output_name]}",
#         # info = f"{RAXML_OUTPUT_FOLDER}/RAxML_info.{config[raxml_output_name]}"
